### ISSUE TITLE
Bug: Unable to Close LangGraph Studio UI on macOS after Error: Failed to start project chainlit-server

### ISSUE THREAD

**Issue by Rich627** [langchain-ai/langgraph-studio#21]
### Description:
I encountered an issue where I am unable to close the LangGraph Studio UI on macOS, even using Activity Monitor. The issue occurred after receiving the following error message:
```
Failed to start project chainlit-server failed to solve: process "/bin/sh -c PYTHONDONTWRITEBYTECODE=1 pip install -no-cache-dir -c /api/constraints.txt requirements.txt" did not complete successfully: exit code: 1
```

### Steps to Reproduce:
1. Start LangGraph Studio on macOS.
2. Attempt to start a project.
3. Encounter the error message above.
4. Try to close the LangGraph Studio UI.
5. Observe that the UI does not close, even when attempting to force quit using Activity Monitor.

### Expected Behavior:
The LangGraph Studio UI should close when attempting to quit the application, either normally or through Activity Monitor.

### Actual Behavior:
The UI remains open and cannot be closed.

### Environment:
- **OS**: macOS 14.5 (23F79)
- **LangGraph Studio Version**: 0.0.11
- **Python Version**: python3.11

**Comment by dqbd** [comment]
This should be fixed with the latest version! Feel free to reopen the issue if it still happens

**Comment by RafaelRViana** [comment]
I came here because I was having same issue. Updated LangGraph Studio to latest version (0.0.16) and this issue was solved. But, now I am getting another similar error.

`failed to solve: process "/bin/sh -c PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt" did not complete successfully: exit code: 1`

Probably its related with this issue.
